### ISSUE TITLE
빌드 관련 오류 (package.yaml)

### ISSUE THREAD

**Issue by JiwonDev** [JiwonDev/haskell-project#3]
빌드 실패시 haskell-project.cabel을 삭제하고  
stack setup
stack build로 다시 빌드하면 됨.

stack에서 package.yaml을 읽고 자동으로 라이브러리 종속성을 관리해줌.
참고로 현재 프로젝트의 package.yaml 내용은 다음과 같음.
```yaml
name:                haskell-project
version:             0.1.0.0
github:              "Github username here/haskell-project"
license:             BSD3
author:              "Author name here"
maintainer:          "Author email here"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/haskell-project#readme>

dependencies:
- base >= 4.7 && < 5 # 런타임 버전
- gloss
- random

library:
  source-dirs: src # 소스 디렉토리 지정. app/Main.hs 진입하고 이 디렉토리를 읽어들임 

executables:
  haskell-project-exe: # 프로젝트 실행할 때 사용할 이름.  변경해도 상관없음
    main:                Main.hs
    source-dirs:         app
    ghc-options: # stack new 했을 때 기본 설정. 따로 변경한 내용은 없음.
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-project

tests:
  haskell-project-test: # 테스트용 이름. Main.hs 대신 Spec.hs 를 진입점으로 사용함. 
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-project

```
